---
- name: Check of availability of the local Repo before python3 installation
  uri:
    url: "{{ local_repo_hostname }}/pub/Distros/"
  register: local_repo_output
  ignore_errors: yes

- name: Message out when unable to install python on the host due to unavailability of the repository
  fail:
    msg: "Unable to install python on the host due to unavailability of the repository"
  when: local_repo_output.status != 200

- name: Display a link to repository 
  debug:
    var: repo_link
  when: repo_link is defined

- name: Downloading and creating a reference to internal Dell Repo for RHEL 6.x version
  raw: "curl {{ local_repo_hostname }}/{{ repo_link }} -o /etc/yum.repos.d/dell-rhel6.repo"
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: repo_link_downloaded_status
  when: (repo_link is defined) and
        ((trimmed_os_name is defined and os[trimmed_os_name]['os_family'] == 'rhel_6') or
        (os_name_via_hostnamectl is defined and os[os_name_via_hostnamectl]['os_family'] == 'rhel_6') or
        (os_name_other is defined and os[os_name_other]['os_family'] == 'rhel_6'))

- name: Downloading and creating a reference to internal Dell Repo for RHEL 7.x version
  raw: "curl {{ local_repo_hostname }}/{{ repo_link }} -o /etc/yum.repos.d/dell-rhel7.repo"
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: repo_link_downloaded_status
  when: (repo_link is defined) and
        ((trimmed_os_name is defined and os[trimmed_os_name]['os_family'] == 'rhel_7') or
        (os_name_via_hostnamectl is defined and os[os_name_via_hostnamectl]['os_family'] == 'rhel_7') or
        (os_name_other is defined and os[os_name_other]['os_family'] == 'rhel_7'))

- name: Block for RHEL 8.x version
  block:
    - name: Create BaseOS.repo configuration file (IF FAILED - Unable to identify the OS)
      template:
        src: BaseOS.repo.j2
        dest: /etc/yum.repos.d/BaseOS.repo

    - name: Create AppStream.repo configuration file (IF FAILED - Unable to identify the OS)
      template:
        src: AppStream.repo.j2
        dest: /etc/yum.repos.d/AppStream.repo
  when: (repo_link is defined) and
        ((trimmed_os_name is defined and os[trimmed_os_name]['os_family'] == 'rhel_8') or
        (os_name_via_hostnamectl is defined and os[os_name_via_hostnamectl]['os_family'] == 'rhel_8') or
        (os_name_other is defined and os[os_name_other]['os_family'] == 'rhel_8'))

- name: Downloading and creating a reference to internal Dell Repo for SLES 12 version
  raw: "curl {{ local_repo_hostname }}/{{ repo_link }} -o /etc/zypp/repos.d/dell-sles12.repo"
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: repo_link_downloaded_status
  when: (repo_link is defined) and
        ((trimmed_os_name is defined and os[trimmed_os_name]['os_family'] == 'suse_12') or
        (os_name_via_hostnamectl is defined and os[os_name_via_hostnamectl]['os_family'] == 'suse_12') or
        (os_name_other is defined and os[os_name_other]['os_family'] == 'suse_12'))
