---
# check procedure if NIS package is installed
- name: Setting a user for the following connection to a host
  set_fact:
    ansible_ssh_user: "{{ vault_user }}"

- name: Setting a password for the user for the following connection to a host
  set_fact:
    ansible_ssh_pass: "{{ vault_password }}"
  no_log: "{{ no_log_value }}"

- name: Checking if the NIS-Client package is installed on the following OSs - CentOS, RHEL, SLES
  shell: rpm -qa | grep nis- || rpm -qa | grep ypbind
  args:
    executable: /bin/bash
    warn: no
  ignore_errors: yes
  register: is_nis_package_installed
  when:
    - other_os == true
    - ubuntu == false

- name: Checking if the NIS-Client package is installed on Ubuntu
  shell: apt list --installed | grep nis || apt list --installed | grep nis-
  args:
    executable: /bin/bash
  become: true
  ignore_errors: yes
  register: is_nis_package_installed_ubuntu
  when:
    - other_os == false
    - ubuntu == true

- name: Setting a fact when NIS Client package has been installed on a host
  set_fact:
    nis_client_package_installed: true
  when: (is_nis_package_installed.stdout is defined and is_nis_package_installed is succeeded) or
        (is_nis_package_installed_ubuntu.stdout is defined and is_nis_package_installed_ubuntu is succeeded)

- name: Checking if the NIS service is running on the following OSs - CentOS, RHEL, SLES
  shell: systemctl status ypbind | grep running
  args:
    executable: /bin/bash
    warn: no
  ignore_errors: yes
  register: is_nis_service_running
  when:
    - nis_client_package_installed == true
    - other_os == true

- name: Checking if the NIS service is running on Ubuntu
  shell: service ypbind status
  args:
    executable: /bin/bash
    warn: no
  ignore_errors: yes
  register: is_nis_service_running_ubuntu
  when:
    - nis_client_package_installed == true
    - ubuntu == true

- name: Setting a fact when NIS client service is running on a host
  set_fact:
    nis_client_running: true
  when: (is_nis_service_running.stdout is defined and is_nis_service_running is succeeded) or
        (is_nis_service_running_ubuntu.stdout is defined and is_nis_service_running_ubuntu is succeeded)

- name: Message out when NIS-client package is present on a host
  debug:
    msg: "NIS-client package is installed on {{ inventory_hostname }}"
  when: nis_client_package_installed == true

- name: Message out when the NIS client service is 'Running' on a host
  debug:
    msg: "Message out when the NIS client is 'Running' on {{ inventory_hostname }}"
  when: nis_client_running == true

- name: Message out when the NIS client service is 'NOT running' for some reason
  debug:
    msg: "Message out when the NIS client service is 'NOT running' for some reason on {{ inventory_hostname }}"
  when: nis_client_package_installed == true and nis_client_running == false