---
# Main task file for role/nis_add_clients
- name: Show awx_job_id variable
  debug:
    msg: "Initial Job ID awx_job_id={{ awx_job_id }}"

- name: Determinate the NIS client location
  include_tasks: determinate_client_location.yml

- name: Get credentials for system
  include_tasks: get_credentials.yml

- name: Check if OS supported
  include_tasks: check_if_os_supported_linux.yml
  when: vault_user is defined or in_json.status == '200'

- name: Running a check to identify what *nix OS family is and check if NIS-Client package presents on a host
  include_tasks: check_nis_package.yml

- name: Running the NIS-Client package installation procedure if absent on the host
  include_tasks: install_nis_package.yml
  when: nis_client_package_installed == false

- name: Joining the NIS-Client to NIS Server
  include_tasks: modify_configs.yml
  when: nis_client_package_installed == true