---
- name: Setting 'domain' record for 'ypdomainname' on SLES
  shell: ypdomainname {{ nis_server_domain }}
  args:
    executable: /bin/bash
    warn: no
  become: true
  register: is_ypdomainname_set

- name: Adding 'domain' record to '/etc/defaultdomain' on SLES
  shell: echo {{ nis_server_domain }} > /etc/defaultdomain
  args:
    executable: /bin/bash
    warn: no
  become: true
  register: is_nis_service_added

- name: Making a copy of '/etc/yp.conf' file for back up purpose
  shell: yes | cp -rf /etc/yp.conf /etc/yp.conf.old
  args:
    executable: /bin/bash
    warn: no
  become: true
  ignore_errors: yes
  register: is_yp_conf_backed_up

- name: Replace a line in /etc/yp.conf for SLES
  replace:
    path: /etc/yp.conf
    regexp: '^domain'
    replace: '#domain'
  become: true
  async: 20
  poll: 5

- name: Adding 'domain' record in '/etc/yp.conf'
  blockinfile:
    path: /etc/yp.conf
    insertafter: EOF
    block: |
      domain {{ nis_server_domain }} server {{ nis_server1_fqhn }}
      domain {{ nis_server_domain }} server {{ nis_server2_fqhn }}
  become: true
  async: 30
  poll: 5

#####
#Replacing the DNS and NTP records for SLES
#####
- name: Commenting the DNS records in '/etc/resolv.conf'
  replace:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    replace: '#nameserver'
    backup: yes
  become: true
  async: 20
  poll: 5

- name: Adding the new DNS records in '/etc/resolv.conf'
  blockinfile:
    path: /etc/resolv.conf
    insertafter: EOF
    block: |
      nameserver {{ dns_primary }}
      nameserver {{ dns_secondary }}
  become: true
  async: 30
  poll: 5

- name: Making a copy of '/etc/ntp.conf' file for back up purpose
  shell: yes | cp -rf /etc/ntp.conf /etc/ntp.conf.old
  args:
    executable: /bin/bash
    warn: no
  become: true
  ignore_errors: yes
  register: is_ntp_conf_backed_up

- name: Commenting the NTP records in '/etc/ntp.conf'
  replace:
    path: /etc/ntp.conf
    regexp: '^server'
    replace: '#server'
  become: true
  async: 20
  poll: 5

- name: Adding the new NTP records in '/etc/ntp.conf'
  blockinfile:
    path: /etc/ntp.conf
    insertafter: EOF
    block: |
      server {{ ntp_primary }} iburst
      server {{ ntp_secondary }} iburst
  become: true
  async: 20
  poll: 5

- name: Reboot host
  reboot:
    reboot_timeout: 120

- name: Running 'ntpq -pn' to check if NTP is reachable (when FAILED - could not get the output for command 'ntpq' on a host)
  shell: ntpq -pn
  args:
    executable: /bin/bash
    warn: no
  become: true
  ignore_errors: yes
  register: ntp_status_sles
  failed_when: ntp_status_sles.stderr is defined and "'Connection refused' in ntp_status_sles.stderr"

- name: Running 'ypwhich' to check the status (when FAILED - could not get the output for command 'ypwhich on a host')
  shell: ypwhich
  args:
    executable: /bin/bash
    warn: no
  become: true
  ignore_errors: yes
  register: ypwhich_status_sles
  failed_when: ypwhich_status_sles.stderr is defined and "'can't get local yp' in ypwhich_status_sles.stderr"