---
- name: Setting a user for the following connection to a host
  set_fact:
    ansible_ssh_user: "{{ vault_user }}"

- name: Setting a password for the user for the following connection to a host
  set_fact:
    ansible_ssh_pass: "{{ vault_password }}"
  no_log: "{{ no_log_value }}"

- name: Display Domain of NIS server
  debug:
    var: nis_server_domain

- name: Display FQDN of NIS server
  debug:
    var: nis_server1_fqhn

- name: Running the procedure for adding the NIS Client to NIS Server for SLES
  include_tasks: modify_config_suse.yml
  when: suse == true

- name: Running the procedure for adding the NIS Client to NIS Server (for CentOS and RHEL family)
  include_tasks: modify_config_rhel_and_centos.yml
  when: (centos == true) or
        (rhel == true)

- name: Running the procedure for adding the NIS Client to NIS Server for Ubuntu
  include_tasks: modify_config_ubuntu.yml
  when: ubuntu == true
